//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}_CATEGORY" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.APPRAISAL_REVIEW"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "category"
})
@XmlRootElement(name = "APPRAISAL_REVIEW")
public class APPRAISALREVIEW {

    @XmlElement(name = "_CATEGORY")
    protected List<CATEGORY> category;
    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "_OriginalAppraisalEffectiveDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String originalAppraisalEffectiveDate;
    @XmlAttribute(name = "_OriginalAppraisedValueAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String originalAppraisedValueAmount;
    @XmlAttribute(name = "_OriginalAppraisedValueAccurateIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String originalAppraisedValueAccurateIndicator;
    @XmlAttribute(name = "_ExtraordinaryAssumptionsDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String extraordinaryAssumptionsDescription;
    @XmlAttribute(name = "_DisagreementDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String disagreementDescription;
    @XmlAttribute(name = "PropertyMarketValueDecreasedIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String propertyMarketValueDecreasedIndicator;
    @XmlAttribute(name = "_ImprovementsCompletedIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String improvementsCompletedIndicator;
    @XmlAttribute(name = "_MarketValueChangeComment")
    @XmlSchemaType(name = "anySimpleType")
    protected String marketValueChangeComment;
    @XmlAttribute(name = "_ValueConclusionComment")
    @XmlSchemaType(name = "anySimpleType")
    protected String valueConclusionComment;

    /**
     * Gets the value of the category property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the category property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCATEGORY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CATEGORY }
     * 
     * 
     */
    public List<CATEGORY> getCATEGORY() {
        if (category == null) {
            category = new ArrayList<CATEGORY>();
        }
        return this.category;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the originalAppraisalEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalAppraisalEffectiveDate() {
        return originalAppraisalEffectiveDate;
    }

    /**
     * Sets the value of the originalAppraisalEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalAppraisalEffectiveDate(String value) {
        this.originalAppraisalEffectiveDate = value;
    }

    /**
     * Gets the value of the originalAppraisedValueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalAppraisedValueAmount() {
        return originalAppraisedValueAmount;
    }

    /**
     * Sets the value of the originalAppraisedValueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalAppraisedValueAmount(String value) {
        this.originalAppraisedValueAmount = value;
    }

    /**
     * Gets the value of the originalAppraisedValueAccurateIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalAppraisedValueAccurateIndicator() {
        return originalAppraisedValueAccurateIndicator;
    }

    /**
     * Sets the value of the originalAppraisedValueAccurateIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalAppraisedValueAccurateIndicator(String value) {
        this.originalAppraisedValueAccurateIndicator = value;
    }

    /**
     * Gets the value of the extraordinaryAssumptionsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraordinaryAssumptionsDescription() {
        return extraordinaryAssumptionsDescription;
    }

    /**
     * Sets the value of the extraordinaryAssumptionsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraordinaryAssumptionsDescription(String value) {
        this.extraordinaryAssumptionsDescription = value;
    }

    /**
     * Gets the value of the disagreementDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisagreementDescription() {
        return disagreementDescription;
    }

    /**
     * Sets the value of the disagreementDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisagreementDescription(String value) {
        this.disagreementDescription = value;
    }

    /**
     * Gets the value of the propertyMarketValueDecreasedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyMarketValueDecreasedIndicator() {
        return propertyMarketValueDecreasedIndicator;
    }

    /**
     * Sets the value of the propertyMarketValueDecreasedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyMarketValueDecreasedIndicator(String value) {
        this.propertyMarketValueDecreasedIndicator = value;
    }

    /**
     * Gets the value of the improvementsCompletedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImprovementsCompletedIndicator() {
        return improvementsCompletedIndicator;
    }

    /**
     * Sets the value of the improvementsCompletedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImprovementsCompletedIndicator(String value) {
        this.improvementsCompletedIndicator = value;
    }

    /**
     * Gets the value of the marketValueChangeComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketValueChangeComment() {
        return marketValueChangeComment;
    }

    /**
     * Sets the value of the marketValueChangeComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketValueChangeComment(String value) {
        this.marketValueChangeComment = value;
    }

    /**
     * Gets the value of the valueConclusionComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueConclusionComment() {
        return valueConclusionComment;
    }

    /**
     * Sets the value of the valueConclusionComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueConclusionComment(String value) {
        this.valueConclusionComment = value;
    }

}
