//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}BASEMENT_FEATURE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ROOM_TYPE_SUMMARY" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.BASEMENT"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "basementfeature",
    "roomtypesummary"
})
@XmlRootElement(name = "BASEMENT")
public class BASEMENT {

    @XmlElement(name = "BASEMENT_FEATURE")
    protected List<BASEMENTFEATURE> basementfeature;
    @XmlElement(name = "ROOM_TYPE_SUMMARY")
    protected List<ROOMTYPESUMMARY> roomtypesummary;
    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "_CeilingMaterialDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String ceilingMaterialDescription;
    @XmlAttribute(name = "_FinishedPercent")
    @XmlSchemaType(name = "anySimpleType")
    protected String finishedPercent;
    @XmlAttribute(name = "_FinishDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String finishDescription;
    @XmlAttribute(name = "_FinishedIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String finishedIndicator;
    @XmlAttribute(name = "_FirstFloorAreaPercent")
    @XmlSchemaType(name = "anySimpleType")
    protected String firstFloorAreaPercent;
    @XmlAttribute(name = "_FloorMaterialDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String floorMaterialDescription;
    @XmlAttribute(name = "_WallMaterialDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String wallMaterialDescription;
    @XmlAttribute(name = "SquareFeetCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String squareFeetCount;

    /**
     * Gets the value of the basementfeature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the basementfeature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBASEMENTFEATURE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BASEMENTFEATURE }
     * 
     * 
     */
    public List<BASEMENTFEATURE> getBASEMENTFEATURE() {
        if (basementfeature == null) {
            basementfeature = new ArrayList<BASEMENTFEATURE>();
        }
        return this.basementfeature;
    }

    /**
     * Gets the value of the roomtypesummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roomtypesummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getROOMTYPESUMMARY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ROOMTYPESUMMARY }
     * 
     * 
     */
    public List<ROOMTYPESUMMARY> getROOMTYPESUMMARY() {
        if (roomtypesummary == null) {
            roomtypesummary = new ArrayList<ROOMTYPESUMMARY>();
        }
        return this.roomtypesummary;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the ceilingMaterialDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCeilingMaterialDescription() {
        return ceilingMaterialDescription;
    }

    /**
     * Sets the value of the ceilingMaterialDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCeilingMaterialDescription(String value) {
        this.ceilingMaterialDescription = value;
    }

    /**
     * Gets the value of the finishedPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinishedPercent() {
        return finishedPercent;
    }

    /**
     * Sets the value of the finishedPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinishedPercent(String value) {
        this.finishedPercent = value;
    }

    /**
     * Gets the value of the finishDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinishDescription() {
        return finishDescription;
    }

    /**
     * Sets the value of the finishDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinishDescription(String value) {
        this.finishDescription = value;
    }

    /**
     * Gets the value of the finishedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinishedIndicator() {
        return finishedIndicator;
    }

    /**
     * Sets the value of the finishedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinishedIndicator(String value) {
        this.finishedIndicator = value;
    }

    /**
     * Gets the value of the firstFloorAreaPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstFloorAreaPercent() {
        return firstFloorAreaPercent;
    }

    /**
     * Sets the value of the firstFloorAreaPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstFloorAreaPercent(String value) {
        this.firstFloorAreaPercent = value;
    }

    /**
     * Gets the value of the floorMaterialDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloorMaterialDescription() {
        return floorMaterialDescription;
    }

    /**
     * Sets the value of the floorMaterialDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloorMaterialDescription(String value) {
        this.floorMaterialDescription = value;
    }

    /**
     * Gets the value of the wallMaterialDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWallMaterialDescription() {
        return wallMaterialDescription;
    }

    /**
     * Sets the value of the wallMaterialDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWallMaterialDescription(String value) {
        this.wallMaterialDescription = value;
    }

    /**
     * Gets the value of the squareFeetCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSquareFeetCount() {
        return squareFeetCount;
    }

    /**
     * Sets the value of the squareFeetCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSquareFeetCount(String value) {
        this.squareFeetCount = value;
    }

}
