//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NEW_IMPROVEMENT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}DEPRECIATION" minOccurs="0"/>
 *         &lt;element ref="{}DATA_IDENTIFICATION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.COST_ANALYSIS"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "newimprovement",
    "depreciation",
    "dataidentification"
})
@XmlRootElement(name = "COST_ANALYSIS")
public class COSTANALYSIS {

    @XmlElement(name = "NEW_IMPROVEMENT")
    protected List<NEWIMPROVEMENT> newimprovement;
    @XmlElement(name = "DEPRECIATION")
    protected DEPRECIATION depreciation;
    @XmlElement(name = "DATA_IDENTIFICATION")
    protected DATAIDENTIFICATION dataidentification;
    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "_Type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "_TypeOtherDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String typeOtherDescription;
    @XmlAttribute(name = "SiteEstimatedValueAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String siteEstimatedValueAmount;
    @XmlAttribute(name = "SiteEstimatedValueComment")
    @XmlSchemaType(name = "anySimpleType")
    protected String siteEstimatedValueComment;
    @XmlAttribute(name = "DataSourceDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String dataSourceDescription;
    @XmlAttribute(name = "DataSourceEffectiveDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String dataSourceEffectiveDate;
    @XmlAttribute(name = "CostServiceQualityRatingDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String costServiceQualityRatingDescription;
    @XmlAttribute(name = "NewImprovementTotalCostAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String newImprovementTotalCostAmount;
    @XmlAttribute(name = "NewImprovementCostMultiplierFactor")
    @XmlSchemaType(name = "anySimpleType")
    protected String newImprovementCostMultiplierFactor;
    @XmlAttribute(name = "NewImprovementCostLocalizedAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String newImprovementCostLocalizedAmount;
    @XmlAttribute(name = "NewImprovementDepreciatedCostAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String newImprovementDepreciatedCostAmount;
    @XmlAttribute(name = "SiteOtherImprovementsAsIsAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String siteOtherImprovementsAsIsAmount;
    @XmlAttribute(name = "ManufacturedHomeInstallationCostAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String manufacturedHomeInstallationCostAmount;
    @XmlAttribute(name = "EstimatedRemainingEconomicLifeYearsCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String estimatedRemainingEconomicLifeYearsCount;
    @XmlAttribute(name = "ValueIndicatedByCostApproachAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String valueIndicatedByCostApproachAmount;
    @XmlAttribute(name = "_Comment")
    @XmlSchemaType(name = "anySimpleType")
    protected String comment;

    /**
     * Gets the value of the newimprovement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the newimprovement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNEWIMPROVEMENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NEWIMPROVEMENT }
     * 
     * 
     */
    public List<NEWIMPROVEMENT> getNEWIMPROVEMENT() {
        if (newimprovement == null) {
            newimprovement = new ArrayList<NEWIMPROVEMENT>();
        }
        return this.newimprovement;
    }

    /**
     * Gets the value of the depreciation property.
     * 
     * @return
     *     possible object is
     *     {@link DEPRECIATION }
     *     
     */
    public DEPRECIATION getDEPRECIATION() {
        return depreciation;
    }

    /**
     * Sets the value of the depreciation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DEPRECIATION }
     *     
     */
    public void setDEPRECIATION(DEPRECIATION value) {
        this.depreciation = value;
    }

    /**
     * Gets the value of the dataidentification property.
     * 
     * @return
     *     possible object is
     *     {@link DATAIDENTIFICATION }
     *     
     */
    public DATAIDENTIFICATION getDATAIDENTIFICATION() {
        return dataidentification;
    }

    /**
     * Sets the value of the dataidentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link DATAIDENTIFICATION }
     *     
     */
    public void setDATAIDENTIFICATION(DATAIDENTIFICATION value) {
        this.dataidentification = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the typeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOtherDescription() {
        return typeOtherDescription;
    }

    /**
     * Sets the value of the typeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOtherDescription(String value) {
        this.typeOtherDescription = value;
    }

    /**
     * Gets the value of the siteEstimatedValueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteEstimatedValueAmount() {
        return siteEstimatedValueAmount;
    }

    /**
     * Sets the value of the siteEstimatedValueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteEstimatedValueAmount(String value) {
        this.siteEstimatedValueAmount = value;
    }

    /**
     * Gets the value of the siteEstimatedValueComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteEstimatedValueComment() {
        return siteEstimatedValueComment;
    }

    /**
     * Sets the value of the siteEstimatedValueComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteEstimatedValueComment(String value) {
        this.siteEstimatedValueComment = value;
    }

    /**
     * Gets the value of the dataSourceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSourceDescription() {
        return dataSourceDescription;
    }

    /**
     * Sets the value of the dataSourceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSourceDescription(String value) {
        this.dataSourceDescription = value;
    }

    /**
     * Gets the value of the dataSourceEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSourceEffectiveDate() {
        return dataSourceEffectiveDate;
    }

    /**
     * Sets the value of the dataSourceEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSourceEffectiveDate(String value) {
        this.dataSourceEffectiveDate = value;
    }

    /**
     * Gets the value of the costServiceQualityRatingDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostServiceQualityRatingDescription() {
        return costServiceQualityRatingDescription;
    }

    /**
     * Sets the value of the costServiceQualityRatingDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostServiceQualityRatingDescription(String value) {
        this.costServiceQualityRatingDescription = value;
    }

    /**
     * Gets the value of the newImprovementTotalCostAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewImprovementTotalCostAmount() {
        return newImprovementTotalCostAmount;
    }

    /**
     * Sets the value of the newImprovementTotalCostAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewImprovementTotalCostAmount(String value) {
        this.newImprovementTotalCostAmount = value;
    }

    /**
     * Gets the value of the newImprovementCostMultiplierFactor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewImprovementCostMultiplierFactor() {
        return newImprovementCostMultiplierFactor;
    }

    /**
     * Sets the value of the newImprovementCostMultiplierFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewImprovementCostMultiplierFactor(String value) {
        this.newImprovementCostMultiplierFactor = value;
    }

    /**
     * Gets the value of the newImprovementCostLocalizedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewImprovementCostLocalizedAmount() {
        return newImprovementCostLocalizedAmount;
    }

    /**
     * Sets the value of the newImprovementCostLocalizedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewImprovementCostLocalizedAmount(String value) {
        this.newImprovementCostLocalizedAmount = value;
    }

    /**
     * Gets the value of the newImprovementDepreciatedCostAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewImprovementDepreciatedCostAmount() {
        return newImprovementDepreciatedCostAmount;
    }

    /**
     * Sets the value of the newImprovementDepreciatedCostAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewImprovementDepreciatedCostAmount(String value) {
        this.newImprovementDepreciatedCostAmount = value;
    }

    /**
     * Gets the value of the siteOtherImprovementsAsIsAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteOtherImprovementsAsIsAmount() {
        return siteOtherImprovementsAsIsAmount;
    }

    /**
     * Sets the value of the siteOtherImprovementsAsIsAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteOtherImprovementsAsIsAmount(String value) {
        this.siteOtherImprovementsAsIsAmount = value;
    }

    /**
     * Gets the value of the manufacturedHomeInstallationCostAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturedHomeInstallationCostAmount() {
        return manufacturedHomeInstallationCostAmount;
    }

    /**
     * Sets the value of the manufacturedHomeInstallationCostAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturedHomeInstallationCostAmount(String value) {
        this.manufacturedHomeInstallationCostAmount = value;
    }

    /**
     * Gets the value of the estimatedRemainingEconomicLifeYearsCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstimatedRemainingEconomicLifeYearsCount() {
        return estimatedRemainingEconomicLifeYearsCount;
    }

    /**
     * Sets the value of the estimatedRemainingEconomicLifeYearsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstimatedRemainingEconomicLifeYearsCount(String value) {
        this.estimatedRemainingEconomicLifeYearsCount = value;
    }

    /**
     * Gets the value of the valueIndicatedByCostApproachAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueIndicatedByCostApproachAmount() {
        return valueIndicatedByCostApproachAmount;
    }

    /**
     * Sets the value of the valueIndicatedByCostApproachAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueIndicatedByCostApproachAmount(String value) {
        this.valueIndicatedByCostApproachAmount = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
