//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.DEPRECIATION"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DEPRECIATION")
public class DEPRECIATION {

    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "_PhysicalPercent")
    @XmlSchemaType(name = "anySimpleType")
    protected String physicalPercent;
    @XmlAttribute(name = "_PhysicalAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String physicalAmount;
    @XmlAttribute(name = "_FunctionalPercent")
    @XmlSchemaType(name = "anySimpleType")
    protected String functionalPercent;
    @XmlAttribute(name = "_FunctionalAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String functionalAmount;
    @XmlAttribute(name = "_ExteriorPercent")
    @XmlSchemaType(name = "anySimpleType")
    protected String exteriorPercent;
    @XmlAttribute(name = "_ExteriorAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String exteriorAmount;
    @XmlAttribute(name = "_TotalAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String totalAmount;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the physicalPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicalPercent() {
        return physicalPercent;
    }

    /**
     * Sets the value of the physicalPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicalPercent(String value) {
        this.physicalPercent = value;
    }

    /**
     * Gets the value of the physicalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicalAmount() {
        return physicalAmount;
    }

    /**
     * Sets the value of the physicalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicalAmount(String value) {
        this.physicalAmount = value;
    }

    /**
     * Gets the value of the functionalPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionalPercent() {
        return functionalPercent;
    }

    /**
     * Sets the value of the functionalPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionalPercent(String value) {
        this.functionalPercent = value;
    }

    /**
     * Gets the value of the functionalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionalAmount() {
        return functionalAmount;
    }

    /**
     * Sets the value of the functionalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionalAmount(String value) {
        this.functionalAmount = value;
    }

    /**
     * Gets the value of the exteriorPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExteriorPercent() {
        return exteriorPercent;
    }

    /**
     * Sets the value of the exteriorPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExteriorPercent(String value) {
        this.exteriorPercent = value;
    }

    /**
     * Gets the value of the exteriorAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExteriorAmount() {
        return exteriorAmount;
    }

    /**
     * Sets the value of the exteriorAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExteriorAmount(String value) {
        this.exteriorAmount = value;
    }

    /**
     * Gets the value of the totalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalAmount() {
        return totalAmount;
    }

    /**
     * Sets the value of the totalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalAmount(String value) {
        this.totalAmount = value;
    }

}
