//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.FLOOD_ZONE"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "FLOOD_ZONE")
public class FLOODZONE {

    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "NFIPFloodZoneIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String nfipFloodZoneIdentifier;
    @XmlAttribute(name = "NFIPMapIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String nfipMapIdentifier;
    @XmlAttribute(name = "NFIPMapPanelDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String nfipMapPanelDate;
    @XmlAttribute(name = "NFIPCommunityName")
    @XmlSchemaType(name = "anySimpleType")
    protected String nfipCommunityName;
    @XmlAttribute(name = "SpecialFloodHazardAreaIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String specialFloodHazardAreaIndicator;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the nfipFloodZoneIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNFIPFloodZoneIdentifier() {
        return nfipFloodZoneIdentifier;
    }

    /**
     * Sets the value of the nfipFloodZoneIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNFIPFloodZoneIdentifier(String value) {
        this.nfipFloodZoneIdentifier = value;
    }

    /**
     * Gets the value of the nfipMapIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNFIPMapIdentifier() {
        return nfipMapIdentifier;
    }

    /**
     * Sets the value of the nfipMapIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNFIPMapIdentifier(String value) {
        this.nfipMapIdentifier = value;
    }

    /**
     * Gets the value of the nfipMapPanelDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNFIPMapPanelDate() {
        return nfipMapPanelDate;
    }

    /**
     * Sets the value of the nfipMapPanelDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNFIPMapPanelDate(String value) {
        this.nfipMapPanelDate = value;
    }

    /**
     * Gets the value of the nfipCommunityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNFIPCommunityName() {
        return nfipCommunityName;
    }

    /**
     * Sets the value of the nfipCommunityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNFIPCommunityName(String value) {
        this.nfipCommunityName = value;
    }

    /**
     * Gets the value of the specialFloodHazardAreaIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialFloodHazardAreaIndicator() {
        return specialFloodHazardAreaIndicator;
    }

    /**
     * Sets the value of the specialFloodHazardAreaIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialFloodHazardAreaIndicator(String value) {
        this.specialFloodHazardAreaIndicator = value;
    }

}
