//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist._IDENTIFICATION"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "_IDENTIFICATION")
public class IDENTIFICATION {

    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "AssessorsParcelIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String assessorsParcelIdentifier;
    @XmlAttribute(name = "AssessorsSecondParcelIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String assessorsSecondParcelIdentifier;
    @XmlAttribute(name = "CountyFIPSCode")
    @XmlSchemaType(name = "anySimpleType")
    protected String countyFIPSCode;
    @XmlAttribute(name = "CensusTractIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String censusTractIdentifier;
    @XmlAttribute(name = "LongitudeNumber")
    @XmlSchemaType(name = "anySimpleType")
    protected String longitudeNumber;
    @XmlAttribute(name = "LatitudeNumber")
    @XmlSchemaType(name = "anySimpleType")
    protected String latitudeNumber;
    @XmlAttribute(name = "MapReferenceIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String mapReferenceIdentifier;
    @XmlAttribute(name = "MapReferenceSecondIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String mapReferenceSecondIdentifier;
    @XmlAttribute(name = "MSAIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String msaIdentifier;
    @XmlAttribute(name = "MunicipalityName")
    @XmlSchemaType(name = "anySimpleType")
    protected String municipalityName;
    @XmlAttribute(name = "SchoolDistrictName")
    @XmlSchemaType(name = "anySimpleType")
    protected String schoolDistrictName;
    @XmlAttribute(name = "StateFIPSCode")
    @XmlSchemaType(name = "anySimpleType")
    protected String stateFIPSCode;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the assessorsParcelIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssessorsParcelIdentifier() {
        return assessorsParcelIdentifier;
    }

    /**
     * Sets the value of the assessorsParcelIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssessorsParcelIdentifier(String value) {
        this.assessorsParcelIdentifier = value;
    }

    /**
     * Gets the value of the assessorsSecondParcelIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssessorsSecondParcelIdentifier() {
        return assessorsSecondParcelIdentifier;
    }

    /**
     * Sets the value of the assessorsSecondParcelIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssessorsSecondParcelIdentifier(String value) {
        this.assessorsSecondParcelIdentifier = value;
    }

    /**
     * Gets the value of the countyFIPSCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountyFIPSCode() {
        return countyFIPSCode;
    }

    /**
     * Sets the value of the countyFIPSCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountyFIPSCode(String value) {
        this.countyFIPSCode = value;
    }

    /**
     * Gets the value of the censusTractIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCensusTractIdentifier() {
        return censusTractIdentifier;
    }

    /**
     * Sets the value of the censusTractIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCensusTractIdentifier(String value) {
        this.censusTractIdentifier = value;
    }

    /**
     * Gets the value of the longitudeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongitudeNumber() {
        return longitudeNumber;
    }

    /**
     * Sets the value of the longitudeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongitudeNumber(String value) {
        this.longitudeNumber = value;
    }

    /**
     * Gets the value of the latitudeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatitudeNumber() {
        return latitudeNumber;
    }

    /**
     * Sets the value of the latitudeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatitudeNumber(String value) {
        this.latitudeNumber = value;
    }

    /**
     * Gets the value of the mapReferenceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMapReferenceIdentifier() {
        return mapReferenceIdentifier;
    }

    /**
     * Sets the value of the mapReferenceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMapReferenceIdentifier(String value) {
        this.mapReferenceIdentifier = value;
    }

    /**
     * Gets the value of the mapReferenceSecondIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMapReferenceSecondIdentifier() {
        return mapReferenceSecondIdentifier;
    }

    /**
     * Sets the value of the mapReferenceSecondIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMapReferenceSecondIdentifier(String value) {
        this.mapReferenceSecondIdentifier = value;
    }

    /**
     * Gets the value of the msaIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSAIdentifier() {
        return msaIdentifier;
    }

    /**
     * Sets the value of the msaIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSAIdentifier(String value) {
        this.msaIdentifier = value;
    }

    /**
     * Gets the value of the municipalityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipalityName() {
        return municipalityName;
    }

    /**
     * Sets the value of the municipalityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipalityName(String value) {
        this.municipalityName = value;
    }

    /**
     * Gets the value of the schoolDistrictName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolDistrictName() {
        return schoolDistrictName;
    }

    /**
     * Sets the value of the schoolDistrictName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolDistrictName(String value) {
        this.schoolDistrictName = value;
    }

    /**
     * Gets the value of the stateFIPSCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateFIPSCode() {
        return stateFIPSCode;
    }

    /**
     * Sets the value of the stateFIPSCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateFIPSCode(String value) {
        this.stateFIPSCode = value;
    }

}
