//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PLATTED_LAND" minOccurs="0"/>
 *         &lt;element ref="{}UNPLATTED_LAND" minOccurs="0"/>
 *         &lt;element ref="{}PARCEL_IDENTIFICATION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist._LEGAL_DESCRIPTION"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "plattedland",
    "unplattedland",
    "parcelidentification"
})
@XmlRootElement(name = "_LEGAL_DESCRIPTION")
public class LEGALDESCRIPTION {

    @XmlElement(name = "PLATTED_LAND")
    protected PLATTEDLAND plattedland;
    @XmlElement(name = "UNPLATTED_LAND")
    protected UNPLATTEDLAND unplattedland;
    @XmlElement(name = "PARCEL_IDENTIFICATION")
    protected PARCELIDENTIFICATION parcelidentification;
    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "_TextDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String textDescription;
    @XmlAttribute(name = "_Type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "_TypeOtherDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String typeOtherDescription;

    /**
     * Gets the value of the plattedland property.
     * 
     * @return
     *     possible object is
     *     {@link PLATTEDLAND }
     *     
     */
    public PLATTEDLAND getPLATTEDLAND() {
        return plattedland;
    }

    /**
     * Sets the value of the plattedland property.
     * 
     * @param value
     *     allowed object is
     *     {@link PLATTEDLAND }
     *     
     */
    public void setPLATTEDLAND(PLATTEDLAND value) {
        this.plattedland = value;
    }

    /**
     * Gets the value of the unplattedland property.
     * 
     * @return
     *     possible object is
     *     {@link UNPLATTEDLAND }
     *     
     */
    public UNPLATTEDLAND getUNPLATTEDLAND() {
        return unplattedland;
    }

    /**
     * Sets the value of the unplattedland property.
     * 
     * @param value
     *     allowed object is
     *     {@link UNPLATTEDLAND }
     *     
     */
    public void setUNPLATTEDLAND(UNPLATTEDLAND value) {
        this.unplattedland = value;
    }

    /**
     * Gets the value of the parcelidentification property.
     * 
     * @return
     *     possible object is
     *     {@link PARCELIDENTIFICATION }
     *     
     */
    public PARCELIDENTIFICATION getPARCELIDENTIFICATION() {
        return parcelidentification;
    }

    /**
     * Sets the value of the parcelidentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PARCELIDENTIFICATION }
     *     
     */
    public void setPARCELIDENTIFICATION(PARCELIDENTIFICATION value) {
        this.parcelidentification = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the textDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextDescription() {
        return textDescription;
    }

    /**
     * Sets the value of the textDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextDescription(String value) {
        this.textDescription = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the typeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOtherDescription() {
        return typeOtherDescription;
    }

    /**
     * Sets the value of the typeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOtherDescription(String value) {
        this.typeOtherDescription = value;
    }

}
