//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.PARSED_STREET_ADDRESS"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "PARSED_STREET_ADDRESS")
public class PARSEDSTREETADDRESS {

    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "_StreetName")
    @XmlSchemaType(name = "anySimpleType")
    protected String streetName;
    @XmlAttribute(name = "_DirectionPrefix")
    @XmlSchemaType(name = "anySimpleType")
    protected String directionPrefix;
    @XmlAttribute(name = "_DirectionSuffix")
    @XmlSchemaType(name = "anySimpleType")
    protected String directionSuffix;
    @XmlAttribute(name = "_StreetSuffix")
    @XmlSchemaType(name = "anySimpleType")
    protected String streetSuffix;
    @XmlAttribute(name = "_HouseNumber")
    @XmlSchemaType(name = "anySimpleType")
    protected String houseNumber;
    @XmlAttribute(name = "_BuildingNumber")
    @XmlSchemaType(name = "anySimpleType")
    protected String buildingNumber;
    @XmlAttribute(name = "_ApartmentOrUnit")
    @XmlSchemaType(name = "anySimpleType")
    protected String apartmentOrUnit;
    @XmlAttribute(name = "_MilitaryAPOFPO")
    @XmlSchemaType(name = "anySimpleType")
    protected String militaryAPOFPO;
    @XmlAttribute(name = "_RuralRoute")
    @XmlSchemaType(name = "anySimpleType")
    protected String ruralRoute;
    @XmlAttribute(name = "_PostOfficeBox")
    @XmlSchemaType(name = "anySimpleType")
    protected String postOfficeBox;
    @XmlAttribute(name = "PlusFourPostalCode")
    @XmlSchemaType(name = "anySimpleType")
    protected String plusFourPostalCode;
    @XmlAttribute(name = "SitusCarrierRouteIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String situsCarrierRouteIdentifier;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the streetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * Sets the value of the streetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetName(String value) {
        this.streetName = value;
    }

    /**
     * Gets the value of the directionPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectionPrefix() {
        return directionPrefix;
    }

    /**
     * Sets the value of the directionPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectionPrefix(String value) {
        this.directionPrefix = value;
    }

    /**
     * Gets the value of the directionSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectionSuffix() {
        return directionSuffix;
    }

    /**
     * Sets the value of the directionSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectionSuffix(String value) {
        this.directionSuffix = value;
    }

    /**
     * Gets the value of the streetSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetSuffix() {
        return streetSuffix;
    }

    /**
     * Sets the value of the streetSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetSuffix(String value) {
        this.streetSuffix = value;
    }

    /**
     * Gets the value of the houseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * Sets the value of the houseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseNumber(String value) {
        this.houseNumber = value;
    }

    /**
     * Gets the value of the buildingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingNumber() {
        return buildingNumber;
    }

    /**
     * Sets the value of the buildingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingNumber(String value) {
        this.buildingNumber = value;
    }

    /**
     * Gets the value of the apartmentOrUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApartmentOrUnit() {
        return apartmentOrUnit;
    }

    /**
     * Sets the value of the apartmentOrUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApartmentOrUnit(String value) {
        this.apartmentOrUnit = value;
    }

    /**
     * Gets the value of the militaryAPOFPO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMilitaryAPOFPO() {
        return militaryAPOFPO;
    }

    /**
     * Sets the value of the militaryAPOFPO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMilitaryAPOFPO(String value) {
        this.militaryAPOFPO = value;
    }

    /**
     * Gets the value of the ruralRoute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuralRoute() {
        return ruralRoute;
    }

    /**
     * Sets the value of the ruralRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuralRoute(String value) {
        this.ruralRoute = value;
    }

    /**
     * Gets the value of the postOfficeBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostOfficeBox() {
        return postOfficeBox;
    }

    /**
     * Sets the value of the postOfficeBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostOfficeBox(String value) {
        this.postOfficeBox = value;
    }

    /**
     * Gets the value of the plusFourPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlusFourPostalCode() {
        return plusFourPostalCode;
    }

    /**
     * Sets the value of the plusFourPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlusFourPostalCode(String value) {
        this.plusFourPostalCode = value;
    }

    /**
     * Gets the value of the situsCarrierRouteIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSitusCarrierRouteIdentifier() {
        return situsCarrierRouteIdentifier;
    }

    /**
     * Sets the value of the situsCarrierRouteIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSitusCarrierRouteIdentifier(String value) {
        this.situsCarrierRouteIdentifier = value;
    }

}
