//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}APPRAISER" minOccurs="0"/>
 *         &lt;element ref="{}SUPERVISOR" minOccurs="0"/>
 *         &lt;element ref="{}REVIEW_APPRAISER" minOccurs="0"/>
 *         &lt;element ref="{}REAL_ESTATE_AGENT" minOccurs="0"/>
 *         &lt;element ref="{}LENDER" minOccurs="0"/>
 *         &lt;element ref="{}BORROWER" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.PARTIES"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "appraiser",
    "supervisor",
    "reviewappraiser",
    "realestateagent",
    "lender",
    "borrower"
})
@XmlRootElement(name = "PARTIES")
public class PARTIES {

    @XmlElement(name = "APPRAISER")
    protected APPRAISER appraiser;
    @XmlElement(name = "SUPERVISOR")
    protected SUPERVISOR supervisor;
    @XmlElement(name = "REVIEW_APPRAISER")
    protected REVIEWAPPRAISER reviewappraiser;
    @XmlElement(name = "REAL_ESTATE_AGENT")
    protected REALESTATEAGENT realestateagent;
    @XmlElement(name = "LENDER")
    protected LENDER lender;
    @XmlElement(name = "BORROWER")
    protected BORROWER borrower;
    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the appraiser property.
     * 
     * @return
     *     possible object is
     *     {@link APPRAISER }
     *     
     */
    public APPRAISER getAPPRAISER() {
        return appraiser;
    }

    /**
     * Sets the value of the appraiser property.
     * 
     * @param value
     *     allowed object is
     *     {@link APPRAISER }
     *     
     */
    public void setAPPRAISER(APPRAISER value) {
        this.appraiser = value;
    }

    /**
     * Gets the value of the supervisor property.
     * 
     * @return
     *     possible object is
     *     {@link SUPERVISOR }
     *     
     */
    public SUPERVISOR getSUPERVISOR() {
        return supervisor;
    }

    /**
     * Sets the value of the supervisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link SUPERVISOR }
     *     
     */
    public void setSUPERVISOR(SUPERVISOR value) {
        this.supervisor = value;
    }

    /**
     * Gets the value of the reviewappraiser property.
     * 
     * @return
     *     possible object is
     *     {@link REVIEWAPPRAISER }
     *     
     */
    public REVIEWAPPRAISER getREVIEWAPPRAISER() {
        return reviewappraiser;
    }

    /**
     * Sets the value of the reviewappraiser property.
     * 
     * @param value
     *     allowed object is
     *     {@link REVIEWAPPRAISER }
     *     
     */
    public void setREVIEWAPPRAISER(REVIEWAPPRAISER value) {
        this.reviewappraiser = value;
    }

    /**
     * Gets the value of the realestateagent property.
     * 
     * @return
     *     possible object is
     *     {@link REALESTATEAGENT }
     *     
     */
    public REALESTATEAGENT getREALESTATEAGENT() {
        return realestateagent;
    }

    /**
     * Sets the value of the realestateagent property.
     * 
     * @param value
     *     allowed object is
     *     {@link REALESTATEAGENT }
     *     
     */
    public void setREALESTATEAGENT(REALESTATEAGENT value) {
        this.realestateagent = value;
    }

    /**
     * Gets the value of the lender property.
     * 
     * @return
     *     possible object is
     *     {@link LENDER }
     *     
     */
    public LENDER getLENDER() {
        return lender;
    }

    /**
     * Sets the value of the lender property.
     * 
     * @param value
     *     allowed object is
     *     {@link LENDER }
     *     
     */
    public void setLENDER(LENDER value) {
        this.lender = value;
    }

    /**
     * Gets the value of the borrower property.
     * 
     * @return
     *     possible object is
     *     {@link BORROWER }
     *     
     */
    public BORROWER getBORROWER() {
        return borrower;
    }

    /**
     * Sets the value of the borrower property.
     * 
     * @param value
     *     allowed object is
     *     {@link BORROWER }
     *     
     */
    public void setBORROWER(BORROWER value) {
        this.borrower = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
