//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}COMPETITIVE_LISTINGS" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.PRICE_FORECASTING"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "competitivelistings"
})
@XmlRootElement(name = "PRICE_FORECASTING")
public class PRICEFORECASTING {

    @XmlElement(name = "COMPETITIVE_LISTINGS")
    protected List<COMPETITIVELISTINGS> competitivelistings;
    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "MarketTrendsAdverseFinancingIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String marketTrendsAdverseFinancingIndicator;
    @XmlAttribute(name = "MarketTrendsHistoricPricesType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String marketTrendsHistoricPricesType;
    @XmlAttribute(name = "MarketTrendsForeclosureActivityIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String marketTrendsForeclosureActivityIndicator;
    @XmlAttribute(name = "MarketTrendsInterestRatesType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String marketTrendsInterestRatesType;
    @XmlAttribute(name = "MarketTrendsSalesActivityType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String marketTrendsSalesActivityType;
    @XmlAttribute(name = "NeighborhoodPropertyValueTrendType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String neighborhoodPropertyValueTrendType;
    @XmlAttribute(name = "NeighborhoodDemandSupplyType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String neighborhoodDemandSupplyType;
    @XmlAttribute(name = "NeighborhoodTypicalMarketingMonthsDurationType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String neighborhoodTypicalMarketingMonthsDurationType;
    @XmlAttribute(name = "NeighborhoodTypicalMarketingDaysDurationType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String neighborhoodTypicalMarketingDaysDurationType;
    @XmlAttribute(name = "PropertyTypicalMarketingDaysDurationType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String propertyTypicalMarketingDaysDurationType;
    @XmlAttribute(name = "MarketTrendsHistoricAnalysisComment")
    @XmlSchemaType(name = "anySimpleType")
    protected String marketTrendsHistoricAnalysisComment;
    @XmlAttribute(name = "MarketTrendsReconciliationComment")
    @XmlSchemaType(name = "anySimpleType")
    protected String marketTrendsReconciliationComment;

    /**
     * Gets the value of the competitivelistings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the competitivelistings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOMPETITIVELISTINGS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link COMPETITIVELISTINGS }
     * 
     * 
     */
    public List<COMPETITIVELISTINGS> getCOMPETITIVELISTINGS() {
        if (competitivelistings == null) {
            competitivelistings = new ArrayList<COMPETITIVELISTINGS>();
        }
        return this.competitivelistings;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the marketTrendsAdverseFinancingIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketTrendsAdverseFinancingIndicator() {
        return marketTrendsAdverseFinancingIndicator;
    }

    /**
     * Sets the value of the marketTrendsAdverseFinancingIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketTrendsAdverseFinancingIndicator(String value) {
        this.marketTrendsAdverseFinancingIndicator = value;
    }

    /**
     * Gets the value of the marketTrendsHistoricPricesType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketTrendsHistoricPricesType() {
        return marketTrendsHistoricPricesType;
    }

    /**
     * Sets the value of the marketTrendsHistoricPricesType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketTrendsHistoricPricesType(String value) {
        this.marketTrendsHistoricPricesType = value;
    }

    /**
     * Gets the value of the marketTrendsForeclosureActivityIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketTrendsForeclosureActivityIndicator() {
        return marketTrendsForeclosureActivityIndicator;
    }

    /**
     * Sets the value of the marketTrendsForeclosureActivityIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketTrendsForeclosureActivityIndicator(String value) {
        this.marketTrendsForeclosureActivityIndicator = value;
    }

    /**
     * Gets the value of the marketTrendsInterestRatesType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketTrendsInterestRatesType() {
        return marketTrendsInterestRatesType;
    }

    /**
     * Sets the value of the marketTrendsInterestRatesType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketTrendsInterestRatesType(String value) {
        this.marketTrendsInterestRatesType = value;
    }

    /**
     * Gets the value of the marketTrendsSalesActivityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketTrendsSalesActivityType() {
        return marketTrendsSalesActivityType;
    }

    /**
     * Sets the value of the marketTrendsSalesActivityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketTrendsSalesActivityType(String value) {
        this.marketTrendsSalesActivityType = value;
    }

    /**
     * Gets the value of the neighborhoodPropertyValueTrendType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeighborhoodPropertyValueTrendType() {
        return neighborhoodPropertyValueTrendType;
    }

    /**
     * Sets the value of the neighborhoodPropertyValueTrendType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeighborhoodPropertyValueTrendType(String value) {
        this.neighborhoodPropertyValueTrendType = value;
    }

    /**
     * Gets the value of the neighborhoodDemandSupplyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeighborhoodDemandSupplyType() {
        return neighborhoodDemandSupplyType;
    }

    /**
     * Sets the value of the neighborhoodDemandSupplyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeighborhoodDemandSupplyType(String value) {
        this.neighborhoodDemandSupplyType = value;
    }

    /**
     * Gets the value of the neighborhoodTypicalMarketingMonthsDurationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeighborhoodTypicalMarketingMonthsDurationType() {
        return neighborhoodTypicalMarketingMonthsDurationType;
    }

    /**
     * Sets the value of the neighborhoodTypicalMarketingMonthsDurationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeighborhoodTypicalMarketingMonthsDurationType(String value) {
        this.neighborhoodTypicalMarketingMonthsDurationType = value;
    }

    /**
     * Gets the value of the neighborhoodTypicalMarketingDaysDurationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNeighborhoodTypicalMarketingDaysDurationType() {
        return neighborhoodTypicalMarketingDaysDurationType;
    }

    /**
     * Sets the value of the neighborhoodTypicalMarketingDaysDurationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNeighborhoodTypicalMarketingDaysDurationType(String value) {
        this.neighborhoodTypicalMarketingDaysDurationType = value;
    }

    /**
     * Gets the value of the propertyTypicalMarketingDaysDurationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyTypicalMarketingDaysDurationType() {
        return propertyTypicalMarketingDaysDurationType;
    }

    /**
     * Sets the value of the propertyTypicalMarketingDaysDurationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyTypicalMarketingDaysDurationType(String value) {
        this.propertyTypicalMarketingDaysDurationType = value;
    }

    /**
     * Gets the value of the marketTrendsHistoricAnalysisComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketTrendsHistoricAnalysisComment() {
        return marketTrendsHistoricAnalysisComment;
    }

    /**
     * Sets the value of the marketTrendsHistoricAnalysisComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketTrendsHistoricAnalysisComment(String value) {
        this.marketTrendsHistoricAnalysisComment = value;
    }

    /**
     * Gets the value of the marketTrendsReconciliationComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketTrendsReconciliationComment() {
        return marketTrendsReconciliationComment;
    }

    /**
     * Sets the value of the marketTrendsReconciliationComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketTrendsReconciliationComment(String value) {
        this.marketTrendsReconciliationComment = value;
    }

}
