//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.PRIOR_SALES"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "PRIOR_SALES")
public class PRIORSALES {

    @XmlAttribute(name = "PropertySalesDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String propertySalesDate;
    @XmlAttribute(name = "PropertySalesAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String propertySalesAmount;
    @XmlAttribute(name = "DataSourceDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String dataSourceDescription;
    @XmlAttribute(name = "DataSourceEffectiveDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String dataSourceEffectiveDate;

    /**
     * Gets the value of the propertySalesDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertySalesDate() {
        return propertySalesDate;
    }

    /**
     * Sets the value of the propertySalesDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertySalesDate(String value) {
        this.propertySalesDate = value;
    }

    /**
     * Gets the value of the propertySalesAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertySalesAmount() {
        return propertySalesAmount;
    }

    /**
     * Sets the value of the propertySalesAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertySalesAmount(String value) {
        this.propertySalesAmount = value;
    }

    /**
     * Gets the value of the dataSourceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSourceDescription() {
        return dataSourceDescription;
    }

    /**
     * Sets the value of the dataSourceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSourceDescription(String value) {
        this.dataSourceDescription = value;
    }

    /**
     * Gets the value of the dataSourceEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSourceEffectiveDate() {
        return dataSourceEffectiveDate;
    }

    /**
     * Sets the value of the dataSourceEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSourceEffectiveDate(String value) {
        this.dataSourceEffectiveDate = value;
    }

}
