//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DEVELOPMENT_STAGE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PROJECT_RATING" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}PROJECT_CAR_STORAGE" minOccurs="0"/>
 *         &lt;element ref="{}PROJECT_ANALYSIS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}_PER_UNIT_FEE" minOccurs="0"/>
 *         &lt;element ref="{}_BLANKET_FINANCING" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}_OCCUPANCY" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.PROJECT"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "developmentstage",
    "projectrating",
    "projectcarstorage",
    "projectanalysis",
    "perunitfee",
    "blanketfinancing",
    "occupancy"
})
@XmlRootElement(name = "PROJECT")
public class PROJECT {

    @XmlElement(name = "DEVELOPMENT_STAGE")
    protected List<DEVELOPMENTSTAGE> developmentstage;
    @XmlElement(name = "PROJECT_RATING")
    protected List<PROJECTRATING> projectrating;
    @XmlElement(name = "PROJECT_CAR_STORAGE")
    protected PROJECTCARSTORAGE projectcarstorage;
    @XmlElement(name = "PROJECT_ANALYSIS")
    protected List<PROJECTANALYSIS> projectanalysis;
    @XmlElement(name = "_PER_UNIT_FEE")
    protected PERUNITFEE perunitfee;
    @XmlElement(name = "_BLANKET_FINANCING")
    protected List<BLANKETFINANCING> blanketfinancing;
    @XmlElement(name = "_OCCUPANCY")
    protected List<OCCUPANCY> occupancy;
    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "_Name")
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(name = "_CommonElementsDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String commonElementsDescription;
    @XmlAttribute(name = "_CommonElementsCompletedIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String commonElementsCompletedIndicator;
    @XmlAttribute(name = "_CommonElementsStatusDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String commonElementsStatusDescription;
    @XmlAttribute(name = "_CommonElementsLeasedIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String commonElementsLeasedIndicator;
    @XmlAttribute(name = "_CommonElementsLeaseTermsDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String commonElementsLeaseTermsDescription;
    @XmlAttribute(name = "_ConditionAndQualityDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String conditionAndQualityDescription;
    @XmlAttribute(name = "_ContainsMultipleDwellingUnitsIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String containsMultipleDwellingUnitsIndicator;
    @XmlAttribute(name = "_ContainsMultipleDwellingUnitsDataSourceDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String containsMultipleDwellingUnitsDataSourceDescription;
    @XmlAttribute(name = "_ConversionIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String conversionIndicator;
    @XmlAttribute(name = "_ConversionDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String conversionDate;
    @XmlAttribute(name = "_ConversionOriginalUseDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String conversionOriginalUseDescription;
    @XmlAttribute(name = "_ClassificationType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String classificationType;
    @XmlAttribute(name = "_ClassificationTypeOtherDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String classificationTypeOtherDescription;
    @XmlAttribute(name = "_CurrentStatusDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String currentStatusDescription;
    @XmlAttribute(name = "_DesignType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String designType;
    @XmlAttribute(name = "_DesignTypeOtherDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String designTypeOtherDescription;
    @XmlAttribute(name = "_DeveloperControlsProjectManagementIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String developerControlsProjectManagementIndicator;
    @XmlAttribute(name = "_DeveloperControlOfProjectManagementDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String developerControlOfProjectManagementDescription;
    @XmlAttribute(name = "_ManagementType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String managementType;
    @XmlAttribute(name = "_ManagementTypeOtherDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String managementTypeOtherDescription;
    @XmlAttribute(name = "_ManagementAgentName")
    @XmlSchemaType(name = "anySimpleType")
    protected String managementAgentName;
    @XmlAttribute(name = "_PhaseIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String phaseIdentifier;
    @XmlAttribute(name = "PropertyCurrentUsageType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String propertyCurrentUsageType;
    @XmlAttribute(name = "_PrimaryOccupancyType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String primaryOccupancyType;
    @XmlAttribute(name = "_UnitDensityPerAcreCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String unitDensityPerAcreCount;
    @XmlAttribute(name = "LivingUnitCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String livingUnitCount;
    @XmlAttribute(name = "ElevatorCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String elevatorCount;
    @XmlAttribute(name = "StoriesCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String storiesCount;
    @XmlAttribute(name = "_DataSourceType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dataSourceType;
    @XmlAttribute(name = "_DataSourceTypeOtherDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String dataSourceTypeOtherDescription;
    @XmlAttribute(name = "DataSourceDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String dataSourceDescription;
    @XmlAttribute(name = "_ConcentratedOwnershipIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String concentratedOwnershipIndicator;
    @XmlAttribute(name = "_ConcentratedOwnershipDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String concentratedOwnershipDescription;
    @XmlAttribute(name = "_CommercialSpaceIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String commercialSpaceIndicator;
    @XmlAttribute(name = "CommercialSpaceDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String commercialSpaceDescription;
    @XmlAttribute(name = "_PartOfMasterAssociationIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String partOfMasterAssociationIndicator;
    @XmlAttribute(name = "_PartOfMasterAssociationDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String partOfMasterAssociationDescription;
    @XmlAttribute(name = "_TotalSharesCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String totalSharesCount;
    @XmlAttribute(name = "_PerUnitFinancingAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String perUnitFinancingAmount;
    @XmlAttribute(name = "_PerUnitLienAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String perUnitLienAmount;
    @XmlAttribute(name = "OwnersWithinProjectMoreThanTwoMonthsDelinquentCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String ownersWithinProjectMoreThanTwoMonthsDelinquentCount;
    @XmlAttribute(name = "_DeveloperTransferConcessionsIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String developerTransferConcessionsIndicator;
    @XmlAttribute(name = "_DeveloperTransferConcessionsDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String developerTransferConcessionsDescription;
    @XmlAttribute(name = "_TaxAbatementsOrExemptionsIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String taxAbatementsOrExemptionsIndicator;
    @XmlAttribute(name = "_TaxAbatementsOrExemptionsDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String taxAbatementsOrExemptionsDescription;
    @XmlAttribute(name = "_StockTransferFeeIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String stockTransferFeeIndicator;
    @XmlAttribute(name = "_StockTransferFeeDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String stockTransferFeeDescription;

    /**
     * Gets the value of the developmentstage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the developmentstage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDEVELOPMENTSTAGE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DEVELOPMENTSTAGE }
     * 
     * 
     */
    public List<DEVELOPMENTSTAGE> getDEVELOPMENTSTAGE() {
        if (developmentstage == null) {
            developmentstage = new ArrayList<DEVELOPMENTSTAGE>();
        }
        return this.developmentstage;
    }

    /**
     * Gets the value of the projectrating property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the projectrating property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPROJECTRATING().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PROJECTRATING }
     * 
     * 
     */
    public List<PROJECTRATING> getPROJECTRATING() {
        if (projectrating == null) {
            projectrating = new ArrayList<PROJECTRATING>();
        }
        return this.projectrating;
    }

    /**
     * Gets the value of the projectcarstorage property.
     * 
     * @return
     *     possible object is
     *     {@link PROJECTCARSTORAGE }
     *     
     */
    public PROJECTCARSTORAGE getPROJECTCARSTORAGE() {
        return projectcarstorage;
    }

    /**
     * Sets the value of the projectcarstorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROJECTCARSTORAGE }
     *     
     */
    public void setPROJECTCARSTORAGE(PROJECTCARSTORAGE value) {
        this.projectcarstorage = value;
    }

    /**
     * Gets the value of the projectanalysis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the projectanalysis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPROJECTANALYSIS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PROJECTANALYSIS }
     * 
     * 
     */
    public List<PROJECTANALYSIS> getPROJECTANALYSIS() {
        if (projectanalysis == null) {
            projectanalysis = new ArrayList<PROJECTANALYSIS>();
        }
        return this.projectanalysis;
    }

    /**
     * Gets the value of the perunitfee property.
     * 
     * @return
     *     possible object is
     *     {@link PERUNITFEE }
     *     
     */
    public PERUNITFEE getPERUNITFEE() {
        return perunitfee;
    }

    /**
     * Sets the value of the perunitfee property.
     * 
     * @param value
     *     allowed object is
     *     {@link PERUNITFEE }
     *     
     */
    public void setPERUNITFEE(PERUNITFEE value) {
        this.perunitfee = value;
    }

    /**
     * Gets the value of the blanketfinancing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blanketfinancing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBLANKETFINANCING().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BLANKETFINANCING }
     * 
     * 
     */
    public List<BLANKETFINANCING> getBLANKETFINANCING() {
        if (blanketfinancing == null) {
            blanketfinancing = new ArrayList<BLANKETFINANCING>();
        }
        return this.blanketfinancing;
    }

    /**
     * Gets the value of the occupancy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the occupancy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOCCUPANCY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OCCUPANCY }
     * 
     * 
     */
    public List<OCCUPANCY> getOCCUPANCY() {
        if (occupancy == null) {
            occupancy = new ArrayList<OCCUPANCY>();
        }
        return this.occupancy;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the commonElementsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonElementsDescription() {
        return commonElementsDescription;
    }

    /**
     * Sets the value of the commonElementsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonElementsDescription(String value) {
        this.commonElementsDescription = value;
    }

    /**
     * Gets the value of the commonElementsCompletedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonElementsCompletedIndicator() {
        return commonElementsCompletedIndicator;
    }

    /**
     * Sets the value of the commonElementsCompletedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonElementsCompletedIndicator(String value) {
        this.commonElementsCompletedIndicator = value;
    }

    /**
     * Gets the value of the commonElementsStatusDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonElementsStatusDescription() {
        return commonElementsStatusDescription;
    }

    /**
     * Sets the value of the commonElementsStatusDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonElementsStatusDescription(String value) {
        this.commonElementsStatusDescription = value;
    }

    /**
     * Gets the value of the commonElementsLeasedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonElementsLeasedIndicator() {
        return commonElementsLeasedIndicator;
    }

    /**
     * Sets the value of the commonElementsLeasedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonElementsLeasedIndicator(String value) {
        this.commonElementsLeasedIndicator = value;
    }

    /**
     * Gets the value of the commonElementsLeaseTermsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommonElementsLeaseTermsDescription() {
        return commonElementsLeaseTermsDescription;
    }

    /**
     * Sets the value of the commonElementsLeaseTermsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommonElementsLeaseTermsDescription(String value) {
        this.commonElementsLeaseTermsDescription = value;
    }

    /**
     * Gets the value of the conditionAndQualityDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionAndQualityDescription() {
        return conditionAndQualityDescription;
    }

    /**
     * Sets the value of the conditionAndQualityDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionAndQualityDescription(String value) {
        this.conditionAndQualityDescription = value;
    }

    /**
     * Gets the value of the containsMultipleDwellingUnitsIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainsMultipleDwellingUnitsIndicator() {
        return containsMultipleDwellingUnitsIndicator;
    }

    /**
     * Sets the value of the containsMultipleDwellingUnitsIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainsMultipleDwellingUnitsIndicator(String value) {
        this.containsMultipleDwellingUnitsIndicator = value;
    }

    /**
     * Gets the value of the containsMultipleDwellingUnitsDataSourceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainsMultipleDwellingUnitsDataSourceDescription() {
        return containsMultipleDwellingUnitsDataSourceDescription;
    }

    /**
     * Sets the value of the containsMultipleDwellingUnitsDataSourceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainsMultipleDwellingUnitsDataSourceDescription(String value) {
        this.containsMultipleDwellingUnitsDataSourceDescription = value;
    }

    /**
     * Gets the value of the conversionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConversionIndicator() {
        return conversionIndicator;
    }

    /**
     * Sets the value of the conversionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConversionIndicator(String value) {
        this.conversionIndicator = value;
    }

    /**
     * Gets the value of the conversionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConversionDate() {
        return conversionDate;
    }

    /**
     * Sets the value of the conversionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConversionDate(String value) {
        this.conversionDate = value;
    }

    /**
     * Gets the value of the conversionOriginalUseDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConversionOriginalUseDescription() {
        return conversionOriginalUseDescription;
    }

    /**
     * Sets the value of the conversionOriginalUseDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConversionOriginalUseDescription(String value) {
        this.conversionOriginalUseDescription = value;
    }

    /**
     * Gets the value of the classificationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationType() {
        return classificationType;
    }

    /**
     * Sets the value of the classificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationType(String value) {
        this.classificationType = value;
    }

    /**
     * Gets the value of the classificationTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationTypeOtherDescription() {
        return classificationTypeOtherDescription;
    }

    /**
     * Sets the value of the classificationTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationTypeOtherDescription(String value) {
        this.classificationTypeOtherDescription = value;
    }

    /**
     * Gets the value of the currentStatusDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentStatusDescription() {
        return currentStatusDescription;
    }

    /**
     * Sets the value of the currentStatusDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentStatusDescription(String value) {
        this.currentStatusDescription = value;
    }

    /**
     * Gets the value of the designType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignType() {
        return designType;
    }

    /**
     * Sets the value of the designType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignType(String value) {
        this.designType = value;
    }

    /**
     * Gets the value of the designTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignTypeOtherDescription() {
        return designTypeOtherDescription;
    }

    /**
     * Sets the value of the designTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignTypeOtherDescription(String value) {
        this.designTypeOtherDescription = value;
    }

    /**
     * Gets the value of the developerControlsProjectManagementIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeveloperControlsProjectManagementIndicator() {
        return developerControlsProjectManagementIndicator;
    }

    /**
     * Sets the value of the developerControlsProjectManagementIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeveloperControlsProjectManagementIndicator(String value) {
        this.developerControlsProjectManagementIndicator = value;
    }

    /**
     * Gets the value of the developerControlOfProjectManagementDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeveloperControlOfProjectManagementDescription() {
        return developerControlOfProjectManagementDescription;
    }

    /**
     * Sets the value of the developerControlOfProjectManagementDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeveloperControlOfProjectManagementDescription(String value) {
        this.developerControlOfProjectManagementDescription = value;
    }

    /**
     * Gets the value of the managementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagementType() {
        return managementType;
    }

    /**
     * Sets the value of the managementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagementType(String value) {
        this.managementType = value;
    }

    /**
     * Gets the value of the managementTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagementTypeOtherDescription() {
        return managementTypeOtherDescription;
    }

    /**
     * Sets the value of the managementTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagementTypeOtherDescription(String value) {
        this.managementTypeOtherDescription = value;
    }

    /**
     * Gets the value of the managementAgentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagementAgentName() {
        return managementAgentName;
    }

    /**
     * Sets the value of the managementAgentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagementAgentName(String value) {
        this.managementAgentName = value;
    }

    /**
     * Gets the value of the phaseIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhaseIdentifier() {
        return phaseIdentifier;
    }

    /**
     * Sets the value of the phaseIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhaseIdentifier(String value) {
        this.phaseIdentifier = value;
    }

    /**
     * Gets the value of the propertyCurrentUsageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyCurrentUsageType() {
        return propertyCurrentUsageType;
    }

    /**
     * Sets the value of the propertyCurrentUsageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyCurrentUsageType(String value) {
        this.propertyCurrentUsageType = value;
    }

    /**
     * Gets the value of the primaryOccupancyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryOccupancyType() {
        return primaryOccupancyType;
    }

    /**
     * Sets the value of the primaryOccupancyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryOccupancyType(String value) {
        this.primaryOccupancyType = value;
    }

    /**
     * Gets the value of the unitDensityPerAcreCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitDensityPerAcreCount() {
        return unitDensityPerAcreCount;
    }

    /**
     * Sets the value of the unitDensityPerAcreCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitDensityPerAcreCount(String value) {
        this.unitDensityPerAcreCount = value;
    }

    /**
     * Gets the value of the livingUnitCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLivingUnitCount() {
        return livingUnitCount;
    }

    /**
     * Sets the value of the livingUnitCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLivingUnitCount(String value) {
        this.livingUnitCount = value;
    }

    /**
     * Gets the value of the elevatorCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElevatorCount() {
        return elevatorCount;
    }

    /**
     * Sets the value of the elevatorCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElevatorCount(String value) {
        this.elevatorCount = value;
    }

    /**
     * Gets the value of the storiesCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoriesCount() {
        return storiesCount;
    }

    /**
     * Sets the value of the storiesCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoriesCount(String value) {
        this.storiesCount = value;
    }

    /**
     * Gets the value of the dataSourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSourceType() {
        return dataSourceType;
    }

    /**
     * Sets the value of the dataSourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSourceType(String value) {
        this.dataSourceType = value;
    }

    /**
     * Gets the value of the dataSourceTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSourceTypeOtherDescription() {
        return dataSourceTypeOtherDescription;
    }

    /**
     * Sets the value of the dataSourceTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSourceTypeOtherDescription(String value) {
        this.dataSourceTypeOtherDescription = value;
    }

    /**
     * Gets the value of the dataSourceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSourceDescription() {
        return dataSourceDescription;
    }

    /**
     * Sets the value of the dataSourceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSourceDescription(String value) {
        this.dataSourceDescription = value;
    }

    /**
     * Gets the value of the concentratedOwnershipIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcentratedOwnershipIndicator() {
        return concentratedOwnershipIndicator;
    }

    /**
     * Sets the value of the concentratedOwnershipIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcentratedOwnershipIndicator(String value) {
        this.concentratedOwnershipIndicator = value;
    }

    /**
     * Gets the value of the concentratedOwnershipDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcentratedOwnershipDescription() {
        return concentratedOwnershipDescription;
    }

    /**
     * Sets the value of the concentratedOwnershipDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcentratedOwnershipDescription(String value) {
        this.concentratedOwnershipDescription = value;
    }

    /**
     * Gets the value of the commercialSpaceIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommercialSpaceIndicator() {
        return commercialSpaceIndicator;
    }

    /**
     * Sets the value of the commercialSpaceIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommercialSpaceIndicator(String value) {
        this.commercialSpaceIndicator = value;
    }

    /**
     * Gets the value of the commercialSpaceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommercialSpaceDescription() {
        return commercialSpaceDescription;
    }

    /**
     * Sets the value of the commercialSpaceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommercialSpaceDescription(String value) {
        this.commercialSpaceDescription = value;
    }

    /**
     * Gets the value of the partOfMasterAssociationIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartOfMasterAssociationIndicator() {
        return partOfMasterAssociationIndicator;
    }

    /**
     * Sets the value of the partOfMasterAssociationIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartOfMasterAssociationIndicator(String value) {
        this.partOfMasterAssociationIndicator = value;
    }

    /**
     * Gets the value of the partOfMasterAssociationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartOfMasterAssociationDescription() {
        return partOfMasterAssociationDescription;
    }

    /**
     * Sets the value of the partOfMasterAssociationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartOfMasterAssociationDescription(String value) {
        this.partOfMasterAssociationDescription = value;
    }

    /**
     * Gets the value of the totalSharesCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalSharesCount() {
        return totalSharesCount;
    }

    /**
     * Sets the value of the totalSharesCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalSharesCount(String value) {
        this.totalSharesCount = value;
    }

    /**
     * Gets the value of the perUnitFinancingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerUnitFinancingAmount() {
        return perUnitFinancingAmount;
    }

    /**
     * Sets the value of the perUnitFinancingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerUnitFinancingAmount(String value) {
        this.perUnitFinancingAmount = value;
    }

    /**
     * Gets the value of the perUnitLienAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerUnitLienAmount() {
        return perUnitLienAmount;
    }

    /**
     * Sets the value of the perUnitLienAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerUnitLienAmount(String value) {
        this.perUnitLienAmount = value;
    }

    /**
     * Gets the value of the ownersWithinProjectMoreThanTwoMonthsDelinquentCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnersWithinProjectMoreThanTwoMonthsDelinquentCount() {
        return ownersWithinProjectMoreThanTwoMonthsDelinquentCount;
    }

    /**
     * Sets the value of the ownersWithinProjectMoreThanTwoMonthsDelinquentCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnersWithinProjectMoreThanTwoMonthsDelinquentCount(String value) {
        this.ownersWithinProjectMoreThanTwoMonthsDelinquentCount = value;
    }

    /**
     * Gets the value of the developerTransferConcessionsIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeveloperTransferConcessionsIndicator() {
        return developerTransferConcessionsIndicator;
    }

    /**
     * Sets the value of the developerTransferConcessionsIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeveloperTransferConcessionsIndicator(String value) {
        this.developerTransferConcessionsIndicator = value;
    }

    /**
     * Gets the value of the developerTransferConcessionsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeveloperTransferConcessionsDescription() {
        return developerTransferConcessionsDescription;
    }

    /**
     * Sets the value of the developerTransferConcessionsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeveloperTransferConcessionsDescription(String value) {
        this.developerTransferConcessionsDescription = value;
    }

    /**
     * Gets the value of the taxAbatementsOrExemptionsIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxAbatementsOrExemptionsIndicator() {
        return taxAbatementsOrExemptionsIndicator;
    }

    /**
     * Sets the value of the taxAbatementsOrExemptionsIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxAbatementsOrExemptionsIndicator(String value) {
        this.taxAbatementsOrExemptionsIndicator = value;
    }

    /**
     * Gets the value of the taxAbatementsOrExemptionsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxAbatementsOrExemptionsDescription() {
        return taxAbatementsOrExemptionsDescription;
    }

    /**
     * Sets the value of the taxAbatementsOrExemptionsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxAbatementsOrExemptionsDescription(String value) {
        this.taxAbatementsOrExemptionsDescription = value;
    }

    /**
     * Gets the value of the stockTransferFeeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStockTransferFeeIndicator() {
        return stockTransferFeeIndicator;
    }

    /**
     * Sets the value of the stockTransferFeeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStockTransferFeeIndicator(String value) {
        this.stockTransferFeeIndicator = value;
    }

    /**
     * Gets the value of the stockTransferFeeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStockTransferFeeDescription() {
        return stockTransferFeeDescription;
    }

    /**
     * Sets the value of the stockTransferFeeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStockTransferFeeDescription(String value) {
        this.stockTransferFeeDescription = value;
    }

}
