//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}_CONDITION_OF_APPRAISAL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}REPAIRS" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist._RECONCILIATION"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "conditionofappraisal",
    "repairs"
})
@XmlRootElement(name = "_RECONCILIATION")
public class RECONCILIATION {

    @XmlElement(name = "_CONDITION_OF_APPRAISAL")
    protected List<CONDITIONOFAPPRAISAL> conditionofappraisal;
    @XmlElement(name = "REPAIRS")
    protected REPAIRS repairs;
    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "_ConditionsComment")
    @XmlSchemaType(name = "anySimpleType")
    protected String conditionsComment;
    @XmlAttribute(name = "_SummaryComment")
    @XmlSchemaType(name = "anySimpleType")
    protected String summaryComment;

    /**
     * Gets the value of the conditionofappraisal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conditionofappraisal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONDITIONOFAPPRAISAL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CONDITIONOFAPPRAISAL }
     * 
     * 
     */
    public List<CONDITIONOFAPPRAISAL> getCONDITIONOFAPPRAISAL() {
        if (conditionofappraisal == null) {
            conditionofappraisal = new ArrayList<CONDITIONOFAPPRAISAL>();
        }
        return this.conditionofappraisal;
    }

    /**
     * Gets the value of the repairs property.
     * 
     * @return
     *     possible object is
     *     {@link REPAIRS }
     *     
     */
    public REPAIRS getREPAIRS() {
        return repairs;
    }

    /**
     * Sets the value of the repairs property.
     * 
     * @param value
     *     allowed object is
     *     {@link REPAIRS }
     *     
     */
    public void setREPAIRS(REPAIRS value) {
        this.repairs = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the conditionsComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionsComment() {
        return conditionsComment;
    }

    /**
     * Sets the value of the conditionsComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionsComment(String value) {
        this.conditionsComment = value;
    }

    /**
     * Gets the value of the summaryComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryComment() {
        return summaryComment;
    }

    /**
     * Sets the value of the summaryComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummaryComment(String value) {
        this.summaryComment = value;
    }

}
