//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FORM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}EMBEDDED_FILE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}REFERENCED_FILE" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.REPORT"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "form",
    "embeddedfile",
    "referencedfile"
})
@XmlRootElement(name = "REPORT")
public class REPORT {

    @XmlElement(name = "FORM")
    protected List<FORM> form;
    @XmlElement(name = "EMBEDDED_FILE")
    protected List<EMBEDDEDFILE> embeddedfile;
    @XmlElement(name = "REFERENCED_FILE")
    protected List<REFERENCEDFILE> referencedfile;
    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "AppraisalSoftwareProductName")
    @XmlSchemaType(name = "anySimpleType")
    protected String appraisalSoftwareProductName;
    @XmlAttribute(name = "AppraisalSoftwareProductVersionIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String appraisalSoftwareProductVersionIdentifier;
    @XmlAttribute(name = "AppraisalFormType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String appraisalFormType;
    @XmlAttribute(name = "AppraisalFormTypeOtherDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String appraisalFormTypeOtherDescription;
    @XmlAttribute(name = "AppraisalFormVersionIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String appraisalFormVersionIdentifier;
    @XmlAttribute(name = "USPAPReportDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String uspapReportDescription;
    @XmlAttribute(name = "AppraiserFileIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String appraiserFileIdentifier;
    @XmlAttribute(name = "AppraiserAdditionalFileIdentifierName")
    @XmlSchemaType(name = "anySimpleType")
    protected String appraiserAdditionalFileIdentifierName;
    @XmlAttribute(name = "AppraiserAdditionalFileIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String appraiserAdditionalFileIdentifier;
    @XmlAttribute(name = "LoanPurposeType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String loanPurposeType;
    @XmlAttribute(name = "OtherLoanPurposeDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String otherLoanPurposeDescription;
    @XmlAttribute(name = "LoanOriginationSystemLoanIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String loanOriginationSystemLoanIdentifier;
    @XmlAttribute(name = "AppraiserReportSignedDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String appraiserReportSignedDate;
    @XmlAttribute(name = "SupervisorReportSignedDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String supervisorReportSignedDate;
    @XmlAttribute(name = "AppraisalScopeOfWorkDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String appraisalScopeOfWorkDescription;
    @XmlAttribute(name = "AppraisalIntendedUserDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String appraisalIntendedUserDescription;
    @XmlAttribute(name = "AppraisalIntendedUseDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String appraisalIntendedUseDescription;
    @XmlAttribute(name = "AppraisalPurposeType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String appraisalPurposeType;
    @XmlAttribute(name = "AppraisalPurposeTypeOtherDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String appraisalPurposeTypeOtherDescription;
    @XmlAttribute(name = "_TitleDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String titleDescription;

    /**
     * Gets the value of the form property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the form property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFORM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FORM }
     * 
     * 
     */
    public List<FORM> getFORM() {
        if (form == null) {
            form = new ArrayList<FORM>();
        }
        return this.form;
    }

    /**
     * Gets the value of the embeddedfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the embeddedfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEMBEDDEDFILE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EMBEDDEDFILE }
     * 
     * 
     */
    public List<EMBEDDEDFILE> getEMBEDDEDFILE() {
        if (embeddedfile == null) {
            embeddedfile = new ArrayList<EMBEDDEDFILE>();
        }
        return this.embeddedfile;
    }

    /**
     * Gets the value of the referencedfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referencedfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREFERENCEDFILE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link REFERENCEDFILE }
     * 
     * 
     */
    public List<REFERENCEDFILE> getREFERENCEDFILE() {
        if (referencedfile == null) {
            referencedfile = new ArrayList<REFERENCEDFILE>();
        }
        return this.referencedfile;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the appraisalSoftwareProductName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraisalSoftwareProductName() {
        return appraisalSoftwareProductName;
    }

    /**
     * Sets the value of the appraisalSoftwareProductName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraisalSoftwareProductName(String value) {
        this.appraisalSoftwareProductName = value;
    }

    /**
     * Gets the value of the appraisalSoftwareProductVersionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraisalSoftwareProductVersionIdentifier() {
        return appraisalSoftwareProductVersionIdentifier;
    }

    /**
     * Sets the value of the appraisalSoftwareProductVersionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraisalSoftwareProductVersionIdentifier(String value) {
        this.appraisalSoftwareProductVersionIdentifier = value;
    }

    /**
     * Gets the value of the appraisalFormType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraisalFormType() {
        return appraisalFormType;
    }

    /**
     * Sets the value of the appraisalFormType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraisalFormType(String value) {
        this.appraisalFormType = value;
    }

    /**
     * Gets the value of the appraisalFormTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraisalFormTypeOtherDescription() {
        return appraisalFormTypeOtherDescription;
    }

    /**
     * Sets the value of the appraisalFormTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraisalFormTypeOtherDescription(String value) {
        this.appraisalFormTypeOtherDescription = value;
    }

    /**
     * Gets the value of the appraisalFormVersionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraisalFormVersionIdentifier() {
        return appraisalFormVersionIdentifier;
    }

    /**
     * Sets the value of the appraisalFormVersionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraisalFormVersionIdentifier(String value) {
        this.appraisalFormVersionIdentifier = value;
    }

    /**
     * Gets the value of the uspapReportDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSPAPReportDescription() {
        return uspapReportDescription;
    }

    /**
     * Sets the value of the uspapReportDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSPAPReportDescription(String value) {
        this.uspapReportDescription = value;
    }

    /**
     * Gets the value of the appraiserFileIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraiserFileIdentifier() {
        return appraiserFileIdentifier;
    }

    /**
     * Sets the value of the appraiserFileIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraiserFileIdentifier(String value) {
        this.appraiserFileIdentifier = value;
    }

    /**
     * Gets the value of the appraiserAdditionalFileIdentifierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraiserAdditionalFileIdentifierName() {
        return appraiserAdditionalFileIdentifierName;
    }

    /**
     * Sets the value of the appraiserAdditionalFileIdentifierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraiserAdditionalFileIdentifierName(String value) {
        this.appraiserAdditionalFileIdentifierName = value;
    }

    /**
     * Gets the value of the appraiserAdditionalFileIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraiserAdditionalFileIdentifier() {
        return appraiserAdditionalFileIdentifier;
    }

    /**
     * Sets the value of the appraiserAdditionalFileIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraiserAdditionalFileIdentifier(String value) {
        this.appraiserAdditionalFileIdentifier = value;
    }

    /**
     * Gets the value of the loanPurposeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanPurposeType() {
        return loanPurposeType;
    }

    /**
     * Sets the value of the loanPurposeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanPurposeType(String value) {
        this.loanPurposeType = value;
    }

    /**
     * Gets the value of the otherLoanPurposeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherLoanPurposeDescription() {
        return otherLoanPurposeDescription;
    }

    /**
     * Sets the value of the otherLoanPurposeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherLoanPurposeDescription(String value) {
        this.otherLoanPurposeDescription = value;
    }

    /**
     * Gets the value of the loanOriginationSystemLoanIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanOriginationSystemLoanIdentifier() {
        return loanOriginationSystemLoanIdentifier;
    }

    /**
     * Sets the value of the loanOriginationSystemLoanIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanOriginationSystemLoanIdentifier(String value) {
        this.loanOriginationSystemLoanIdentifier = value;
    }

    /**
     * Gets the value of the appraiserReportSignedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraiserReportSignedDate() {
        return appraiserReportSignedDate;
    }

    /**
     * Sets the value of the appraiserReportSignedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraiserReportSignedDate(String value) {
        this.appraiserReportSignedDate = value;
    }

    /**
     * Gets the value of the supervisorReportSignedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupervisorReportSignedDate() {
        return supervisorReportSignedDate;
    }

    /**
     * Sets the value of the supervisorReportSignedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupervisorReportSignedDate(String value) {
        this.supervisorReportSignedDate = value;
    }

    /**
     * Gets the value of the appraisalScopeOfWorkDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraisalScopeOfWorkDescription() {
        return appraisalScopeOfWorkDescription;
    }

    /**
     * Sets the value of the appraisalScopeOfWorkDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraisalScopeOfWorkDescription(String value) {
        this.appraisalScopeOfWorkDescription = value;
    }

    /**
     * Gets the value of the appraisalIntendedUserDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraisalIntendedUserDescription() {
        return appraisalIntendedUserDescription;
    }

    /**
     * Sets the value of the appraisalIntendedUserDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraisalIntendedUserDescription(String value) {
        this.appraisalIntendedUserDescription = value;
    }

    /**
     * Gets the value of the appraisalIntendedUseDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraisalIntendedUseDescription() {
        return appraisalIntendedUseDescription;
    }

    /**
     * Sets the value of the appraisalIntendedUseDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraisalIntendedUseDescription(String value) {
        this.appraisalIntendedUseDescription = value;
    }

    /**
     * Gets the value of the appraisalPurposeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraisalPurposeType() {
        return appraisalPurposeType;
    }

    /**
     * Sets the value of the appraisalPurposeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraisalPurposeType(String value) {
        this.appraisalPurposeType = value;
    }

    /**
     * Gets the value of the appraisalPurposeTypeOtherDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppraisalPurposeTypeOtherDescription() {
        return appraisalPurposeTypeOtherDescription;
    }

    /**
     * Sets the value of the appraisalPurposeTypeOtherDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppraisalPurposeTypeOtherDescription(String value) {
        this.appraisalPurposeTypeOtherDescription = value;
    }

    /**
     * Gets the value of the titleDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleDescription() {
        return titleDescription;
    }

    /**
     * Sets the value of the titleDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleDescription(String value) {
        this.titleDescription = value;
    }

}
