//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.SALES_CONTRACT"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "SALES_CONTRACT")
public class SALESCONTRACT {

    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "_Date")
    @XmlSchemaType(name = "anySimpleType")
    protected String date;
    @XmlAttribute(name = "_Amount")
    @XmlSchemaType(name = "anySimpleType")
    protected String amount;
    @XmlAttribute(name = "_ConditionsOfSaleDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String conditionsOfSaleDescription;
    @XmlAttribute(name = "_ReviewedIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String reviewedIndicator;
    @XmlAttribute(name = "_ReviewComment")
    @XmlSchemaType(name = "anySimpleType")
    protected String reviewComment;
    @XmlAttribute(name = "_TermsAndConditionsConsistentWithTheLocalMarketIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String termsAndConditionsConsistentWithTheLocalMarketIndicator;
    @XmlAttribute(name = "SellerIsOwnerIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sellerIsOwnerIndicator;
    @XmlAttribute(name = "SalesConcessionIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String salesConcessionIndicator;
    @XmlAttribute(name = "DataSourceDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String dataSourceDescription;
    @XmlAttribute(name = "SalesConcessionDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String salesConcessionDescription;
    @XmlAttribute(name = "_RetailerName")
    @XmlSchemaType(name = "anySimpleType")
    protected String retailerName;
    @XmlAttribute(name = "_InvoiceReviewedIndicator")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String invoiceReviewedIndicator;
    @XmlAttribute(name = "_InvoiceReviewComment")
    @XmlSchemaType(name = "anySimpleType")
    protected String invoiceReviewComment;
    @XmlAttribute(name = "SalesConcessionAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String salesConcessionAmount;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the conditionsOfSaleDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditionsOfSaleDescription() {
        return conditionsOfSaleDescription;
    }

    /**
     * Sets the value of the conditionsOfSaleDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditionsOfSaleDescription(String value) {
        this.conditionsOfSaleDescription = value;
    }

    /**
     * Gets the value of the reviewedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewedIndicator() {
        return reviewedIndicator;
    }

    /**
     * Sets the value of the reviewedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewedIndicator(String value) {
        this.reviewedIndicator = value;
    }

    /**
     * Gets the value of the reviewComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewComment() {
        return reviewComment;
    }

    /**
     * Sets the value of the reviewComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewComment(String value) {
        this.reviewComment = value;
    }

    /**
     * Gets the value of the termsAndConditionsConsistentWithTheLocalMarketIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermsAndConditionsConsistentWithTheLocalMarketIndicator() {
        return termsAndConditionsConsistentWithTheLocalMarketIndicator;
    }

    /**
     * Sets the value of the termsAndConditionsConsistentWithTheLocalMarketIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermsAndConditionsConsistentWithTheLocalMarketIndicator(String value) {
        this.termsAndConditionsConsistentWithTheLocalMarketIndicator = value;
    }

    /**
     * Gets the value of the sellerIsOwnerIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerIsOwnerIndicator() {
        return sellerIsOwnerIndicator;
    }

    /**
     * Sets the value of the sellerIsOwnerIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerIsOwnerIndicator(String value) {
        this.sellerIsOwnerIndicator = value;
    }

    /**
     * Gets the value of the salesConcessionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesConcessionIndicator() {
        return salesConcessionIndicator;
    }

    /**
     * Sets the value of the salesConcessionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesConcessionIndicator(String value) {
        this.salesConcessionIndicator = value;
    }

    /**
     * Gets the value of the dataSourceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSourceDescription() {
        return dataSourceDescription;
    }

    /**
     * Sets the value of the dataSourceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSourceDescription(String value) {
        this.dataSourceDescription = value;
    }

    /**
     * Gets the value of the salesConcessionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesConcessionDescription() {
        return salesConcessionDescription;
    }

    /**
     * Sets the value of the salesConcessionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesConcessionDescription(String value) {
        this.salesConcessionDescription = value;
    }

    /**
     * Gets the value of the retailerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetailerName() {
        return retailerName;
    }

    /**
     * Sets the value of the retailerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetailerName(String value) {
        this.retailerName = value;
    }

    /**
     * Gets the value of the invoiceReviewedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceReviewedIndicator() {
        return invoiceReviewedIndicator;
    }

    /**
     * Sets the value of the invoiceReviewedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceReviewedIndicator(String value) {
        this.invoiceReviewedIndicator = value;
    }

    /**
     * Gets the value of the invoiceReviewComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceReviewComment() {
        return invoiceReviewComment;
    }

    /**
     * Sets the value of the invoiceReviewComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceReviewComment(String value) {
        this.invoiceReviewComment = value;
    }

    /**
     * Gets the value of the salesConcessionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesConcessionAmount() {
        return salesConcessionAmount;
    }

    /**
     * Sets the value of the salesConcessionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesConcessionAmount(String value) {
        this.salesConcessionAmount = value;
    }

}
