//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}OTHER_FEATURE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}RESEARCH" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}COMPARABLE_SALE" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.SALES_COMPARISON"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "otherfeature",
    "research",
    "comparablesale"
})
@XmlRootElement(name = "SALES_COMPARISON")
public class SALESCOMPARISON {

    @XmlElement(name = "OTHER_FEATURE")
    protected List<OTHERFEATURE> otherfeature;
    @XmlElement(name = "RESEARCH")
    protected List<RESEARCH> research;
    @XmlElement(name = "COMPARABLE_SALE")
    protected List<COMPARABLESALE> comparablesale;
    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "ValueIndicatedBySalesComparisonApproachAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String valueIndicatedBySalesComparisonApproachAmount;
    @XmlAttribute(name = "_Comment")
    @XmlSchemaType(name = "anySimpleType")
    protected String comment;
    @XmlAttribute(name = "_CurrentSalesAgreementAnalysisComment")
    @XmlSchemaType(name = "anySimpleType")
    protected String currentSalesAgreementAnalysisComment;
    @XmlAttribute(name = "_UnitOfMeasureDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String unitOfMeasureDescription;
    @XmlAttribute(name = "_ValuePerUnitAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String valuePerUnitAmount;
    @XmlAttribute(name = "_TotalUnitValueAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String totalUnitValueAmount;
    @XmlAttribute(name = "_ValuePerRoomAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String valuePerRoomAmount;
    @XmlAttribute(name = "_TotalRoomValueAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String totalRoomValueAmount;
    @XmlAttribute(name = "_ValuePerBedroomAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String valuePerBedroomAmount;
    @XmlAttribute(name = "_TotalBedroomValueAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String totalBedroomValueAmount;
    @XmlAttribute(name = "_ValuePerGrossBuildingAreaAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String valuePerGrossBuildingAreaAmount;
    @XmlAttribute(name = "_TotalGrossBuildingAreaValueAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String totalGrossBuildingAreaValueAmount;

    /**
     * Gets the value of the otherfeature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherfeature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOTHERFEATURE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OTHERFEATURE }
     * 
     * 
     */
    public List<OTHERFEATURE> getOTHERFEATURE() {
        if (otherfeature == null) {
            otherfeature = new ArrayList<OTHERFEATURE>();
        }
        return this.otherfeature;
    }

    /**
     * Gets the value of the research property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the research property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRESEARCH().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RESEARCH }
     * 
     * 
     */
    public List<RESEARCH> getRESEARCH() {
        if (research == null) {
            research = new ArrayList<RESEARCH>();
        }
        return this.research;
    }

    /**
     * Gets the value of the comparablesale property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comparablesale property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCOMPARABLESALE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link COMPARABLESALE }
     * 
     * 
     */
    public List<COMPARABLESALE> getCOMPARABLESALE() {
        if (comparablesale == null) {
            comparablesale = new ArrayList<COMPARABLESALE>();
        }
        return this.comparablesale;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the valueIndicatedBySalesComparisonApproachAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueIndicatedBySalesComparisonApproachAmount() {
        return valueIndicatedBySalesComparisonApproachAmount;
    }

    /**
     * Sets the value of the valueIndicatedBySalesComparisonApproachAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueIndicatedBySalesComparisonApproachAmount(String value) {
        this.valueIndicatedBySalesComparisonApproachAmount = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the currentSalesAgreementAnalysisComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentSalesAgreementAnalysisComment() {
        return currentSalesAgreementAnalysisComment;
    }

    /**
     * Sets the value of the currentSalesAgreementAnalysisComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentSalesAgreementAnalysisComment(String value) {
        this.currentSalesAgreementAnalysisComment = value;
    }

    /**
     * Gets the value of the unitOfMeasureDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasureDescription() {
        return unitOfMeasureDescription;
    }

    /**
     * Sets the value of the unitOfMeasureDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasureDescription(String value) {
        this.unitOfMeasureDescription = value;
    }

    /**
     * Gets the value of the valuePerUnitAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuePerUnitAmount() {
        return valuePerUnitAmount;
    }

    /**
     * Sets the value of the valuePerUnitAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuePerUnitAmount(String value) {
        this.valuePerUnitAmount = value;
    }

    /**
     * Gets the value of the totalUnitValueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalUnitValueAmount() {
        return totalUnitValueAmount;
    }

    /**
     * Sets the value of the totalUnitValueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalUnitValueAmount(String value) {
        this.totalUnitValueAmount = value;
    }

    /**
     * Gets the value of the valuePerRoomAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuePerRoomAmount() {
        return valuePerRoomAmount;
    }

    /**
     * Sets the value of the valuePerRoomAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuePerRoomAmount(String value) {
        this.valuePerRoomAmount = value;
    }

    /**
     * Gets the value of the totalRoomValueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalRoomValueAmount() {
        return totalRoomValueAmount;
    }

    /**
     * Sets the value of the totalRoomValueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalRoomValueAmount(String value) {
        this.totalRoomValueAmount = value;
    }

    /**
     * Gets the value of the valuePerBedroomAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuePerBedroomAmount() {
        return valuePerBedroomAmount;
    }

    /**
     * Sets the value of the valuePerBedroomAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuePerBedroomAmount(String value) {
        this.valuePerBedroomAmount = value;
    }

    /**
     * Gets the value of the totalBedroomValueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalBedroomValueAmount() {
        return totalBedroomValueAmount;
    }

    /**
     * Sets the value of the totalBedroomValueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalBedroomValueAmount(String value) {
        this.totalBedroomValueAmount = value;
    }

    /**
     * Gets the value of the valuePerGrossBuildingAreaAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuePerGrossBuildingAreaAmount() {
        return valuePerGrossBuildingAreaAmount;
    }

    /**
     * Sets the value of the valuePerGrossBuildingAreaAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuePerGrossBuildingAreaAmount(String value) {
        this.valuePerGrossBuildingAreaAmount = value;
    }

    /**
     * Gets the value of the totalGrossBuildingAreaValueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalGrossBuildingAreaValueAmount() {
        return totalGrossBuildingAreaValueAmount;
    }

    /**
     * Sets the value of the totalGrossBuildingAreaValueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalGrossBuildingAreaValueAmount(String value) {
        this.totalGrossBuildingAreaValueAmount = value;
    }

}
