//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}STRUCTURE_ANALYSIS_RATING" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.STRUCTURE_ANALYSIS"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "structureanalysisrating"
})
@XmlRootElement(name = "STRUCTURE_ANALYSIS")
public class STRUCTUREANALYSIS {

    @XmlElement(name = "STRUCTURE_ANALYSIS_RATING")
    protected STRUCTUREANALYSISRATING structureanalysisrating;
    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "EffectiveAgeRangeHighYearsCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String effectiveAgeRangeHighYearsCount;
    @XmlAttribute(name = "EffectiveAgeRangeLowYearsCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String effectiveAgeRangeLowYearsCount;
    @XmlAttribute(name = "EffectiveAgeYearsCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String effectiveAgeYearsCount;
    @XmlAttribute(name = "RemainingEconomicLifeRangeHighYearsCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String remainingEconomicLifeRangeHighYearsCount;
    @XmlAttribute(name = "RemainingEconomicLifeRangeLowYearsCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String remainingEconomicLifeRangeLowYearsCount;

    /**
     * Gets the value of the structureanalysisrating property.
     * 
     * @return
     *     possible object is
     *     {@link STRUCTUREANALYSISRATING }
     *     
     */
    public STRUCTUREANALYSISRATING getSTRUCTUREANALYSISRATING() {
        return structureanalysisrating;
    }

    /**
     * Sets the value of the structureanalysisrating property.
     * 
     * @param value
     *     allowed object is
     *     {@link STRUCTUREANALYSISRATING }
     *     
     */
    public void setSTRUCTUREANALYSISRATING(STRUCTUREANALYSISRATING value) {
        this.structureanalysisrating = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the effectiveAgeRangeHighYearsCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveAgeRangeHighYearsCount() {
        return effectiveAgeRangeHighYearsCount;
    }

    /**
     * Sets the value of the effectiveAgeRangeHighYearsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveAgeRangeHighYearsCount(String value) {
        this.effectiveAgeRangeHighYearsCount = value;
    }

    /**
     * Gets the value of the effectiveAgeRangeLowYearsCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveAgeRangeLowYearsCount() {
        return effectiveAgeRangeLowYearsCount;
    }

    /**
     * Sets the value of the effectiveAgeRangeLowYearsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveAgeRangeLowYearsCount(String value) {
        this.effectiveAgeRangeLowYearsCount = value;
    }

    /**
     * Gets the value of the effectiveAgeYearsCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveAgeYearsCount() {
        return effectiveAgeYearsCount;
    }

    /**
     * Sets the value of the effectiveAgeYearsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveAgeYearsCount(String value) {
        this.effectiveAgeYearsCount = value;
    }

    /**
     * Gets the value of the remainingEconomicLifeRangeHighYearsCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemainingEconomicLifeRangeHighYearsCount() {
        return remainingEconomicLifeRangeHighYearsCount;
    }

    /**
     * Sets the value of the remainingEconomicLifeRangeHighYearsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemainingEconomicLifeRangeHighYearsCount(String value) {
        this.remainingEconomicLifeRangeHighYearsCount = value;
    }

    /**
     * Gets the value of the remainingEconomicLifeRangeLowYearsCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemainingEconomicLifeRangeLowYearsCount() {
        return remainingEconomicLifeRangeLowYearsCount;
    }

    /**
     * Sets the value of the remainingEconomicLifeRangeLowYearsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemainingEconomicLifeRangeLowYearsCount(String value) {
        this.remainingEconomicLifeRangeLowYearsCount = value;
    }

}
