//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.UNIT_RENT_SCHEDULE"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "UNIT_RENT_SCHEDULE")
public class UNITRENTSCHEDULE {

    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "UnitSequenceIdentifier")
    @XmlSchemaType(name = "anySimpleType")
    protected String unitSequenceIdentifier;
    @XmlAttribute(name = "LeaseStartDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String leaseStartDate;
    @XmlAttribute(name = "LeaseExpirationDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String leaseExpirationDate;
    @XmlAttribute(name = "UnitUnfurnishedActualRentAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String unitUnfurnishedActualRentAmount;
    @XmlAttribute(name = "UnitFurnishedActualRentAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String unitFurnishedActualRentAmount;
    @XmlAttribute(name = "UnitActualRentAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String unitActualRentAmount;
    @XmlAttribute(name = "UnitUnfurnishedMarketRentAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String unitUnfurnishedMarketRentAmount;
    @XmlAttribute(name = "UnitFurnishedMarketRentAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String unitFurnishedMarketRentAmount;
    @XmlAttribute(name = "UnitMarketRentAmount")
    @XmlSchemaType(name = "anySimpleType")
    protected String unitMarketRentAmount;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the unitSequenceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitSequenceIdentifier() {
        return unitSequenceIdentifier;
    }

    /**
     * Sets the value of the unitSequenceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitSequenceIdentifier(String value) {
        this.unitSequenceIdentifier = value;
    }

    /**
     * Gets the value of the leaseStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeaseStartDate() {
        return leaseStartDate;
    }

    /**
     * Sets the value of the leaseStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeaseStartDate(String value) {
        this.leaseStartDate = value;
    }

    /**
     * Gets the value of the leaseExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeaseExpirationDate() {
        return leaseExpirationDate;
    }

    /**
     * Sets the value of the leaseExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeaseExpirationDate(String value) {
        this.leaseExpirationDate = value;
    }

    /**
     * Gets the value of the unitUnfurnishedActualRentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitUnfurnishedActualRentAmount() {
        return unitUnfurnishedActualRentAmount;
    }

    /**
     * Sets the value of the unitUnfurnishedActualRentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitUnfurnishedActualRentAmount(String value) {
        this.unitUnfurnishedActualRentAmount = value;
    }

    /**
     * Gets the value of the unitFurnishedActualRentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitFurnishedActualRentAmount() {
        return unitFurnishedActualRentAmount;
    }

    /**
     * Sets the value of the unitFurnishedActualRentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitFurnishedActualRentAmount(String value) {
        this.unitFurnishedActualRentAmount = value;
    }

    /**
     * Gets the value of the unitActualRentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitActualRentAmount() {
        return unitActualRentAmount;
    }

    /**
     * Sets the value of the unitActualRentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitActualRentAmount(String value) {
        this.unitActualRentAmount = value;
    }

    /**
     * Gets the value of the unitUnfurnishedMarketRentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitUnfurnishedMarketRentAmount() {
        return unitUnfurnishedMarketRentAmount;
    }

    /**
     * Sets the value of the unitUnfurnishedMarketRentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitUnfurnishedMarketRentAmount(String value) {
        this.unitUnfurnishedMarketRentAmount = value;
    }

    /**
     * Gets the value of the unitFurnishedMarketRentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitFurnishedMarketRentAmount() {
        return unitFurnishedMarketRentAmount;
    }

    /**
     * Sets the value of the unitFurnishedMarketRentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitFurnishedMarketRentAmount(String value) {
        this.unitFurnishedMarketRentAmount = value;
    }

    /**
     * Gets the value of the unitMarketRentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitMarketRentAmount() {
        return unitMarketRentAmount;
    }

    /**
     * Sets the value of the unitMarketRentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitMarketRentAmount(String value) {
        this.unitMarketRentAmount = value;
    }

}
