//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.13 at 09:07:28 PM EST 
//


package com.accure.mismo.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}COST_ANALYSIS" minOccurs="0"/>
 *         &lt;element ref="{}SALES_COMPARISON" minOccurs="0"/>
 *         &lt;element ref="{}INCOME_ANALYSIS" minOccurs="0"/>
 *         &lt;element ref="{}PRICE_FORECASTING" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.VALUATION_METHODS"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "costanalysis",
    "salescomparison",
    "incomeanalysis",
    "priceforecasting"
})
@XmlRootElement(name = "VALUATION_METHODS")
public class VALUATIONMETHODS {

    @XmlElement(name = "COST_ANALYSIS")
    protected COSTANALYSIS costanalysis;
    @XmlElement(name = "SALES_COMPARISON")
    protected SALESCOMPARISON salescomparison;
    @XmlElement(name = "INCOME_ANALYSIS")
    protected INCOMEANALYSIS incomeanalysis;
    @XmlElement(name = "PRICE_FORECASTING")
    protected PRICEFORECASTING priceforecasting;
    @XmlAttribute(name = "_ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "_AdditionalDescription")
    @XmlSchemaType(name = "anySimpleType")
    protected String additionalDescription;

    /**
     * Gets the value of the costanalysis property.
     * 
     * @return
     *     possible object is
     *     {@link COSTANALYSIS }
     *     
     */
    public COSTANALYSIS getCOSTANALYSIS() {
        return costanalysis;
    }

    /**
     * Sets the value of the costanalysis property.
     * 
     * @param value
     *     allowed object is
     *     {@link COSTANALYSIS }
     *     
     */
    public void setCOSTANALYSIS(COSTANALYSIS value) {
        this.costanalysis = value;
    }

    /**
     * Gets the value of the salescomparison property.
     * 
     * @return
     *     possible object is
     *     {@link SALESCOMPARISON }
     *     
     */
    public SALESCOMPARISON getSALESCOMPARISON() {
        return salescomparison;
    }

    /**
     * Sets the value of the salescomparison property.
     * 
     * @param value
     *     allowed object is
     *     {@link SALESCOMPARISON }
     *     
     */
    public void setSALESCOMPARISON(SALESCOMPARISON value) {
        this.salescomparison = value;
    }

    /**
     * Gets the value of the incomeanalysis property.
     * 
     * @return
     *     possible object is
     *     {@link INCOMEANALYSIS }
     *     
     */
    public INCOMEANALYSIS getINCOMEANALYSIS() {
        return incomeanalysis;
    }

    /**
     * Sets the value of the incomeanalysis property.
     * 
     * @param value
     *     allowed object is
     *     {@link INCOMEANALYSIS }
     *     
     */
    public void setINCOMEANALYSIS(INCOMEANALYSIS value) {
        this.incomeanalysis = value;
    }

    /**
     * Gets the value of the priceforecasting property.
     * 
     * @return
     *     possible object is
     *     {@link PRICEFORECASTING }
     *     
     */
    public PRICEFORECASTING getPRICEFORECASTING() {
        return priceforecasting;
    }

    /**
     * Sets the value of the priceforecasting property.
     * 
     * @param value
     *     allowed object is
     *     {@link PRICEFORECASTING }
     *     
     */
    public void setPRICEFORECASTING(PRICEFORECASTING value) {
        this.priceforecasting = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the additionalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalDescription() {
        return additionalDescription;
    }

    /**
     * Sets the value of the additionalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalDescription(String value) {
        this.additionalDescription = value;
    }

}
